### ISSUE TITLE
did it work for rails 4.1?

### ISSUE THREAD

**Issue by TangMonk** [rails/web-console#103]

**Comment by gsamokovarov** [comment]
It generally should :) Can you give a bit more context on what are you trying to do?

**Comment by TangMonk** [comment]
When I insert ```<%= console %>``` to erb file, and reload the view, not works

```
undefined local variable or method `console' 
```

**Comment by danieldimitrov** [comment]
Do you have `gem 'web-console', '~> 2.0'` in your Gemfile? I tried it in 4.1.8. and it works pretty well.

**Comment by gsamokovarov** [comment]
I don't think this is an issue. If you have reasons to believe so, please reopen it with a bit more context of what's going on.
