### ISSUE TITLE
IP Whitelist is not enforced on exceptions

### ISSUE THREAD

**Issue by urmorae** [rails/web-console#108]
Rails 4.2, web_console 2.0.0 if exception occures, IP whitelist is ignored and console is displayed no matter the user IP.

There's a second initialization of console_session variable,  not wrapped in "if allowed?"

In lib/action_dispatch/debug_exceptions.rb (around line 54):

if env['action_dispatch.show_detailed_exceptions']
  request = Request.new(env)
  if allowed?(request)
    console_session = WebConsole::REPLSession.create(
    binding: wrapper.exception.bindings.first,
    binding_stack: exception.bindings
  )
  end

  traces = wrapper.traces
  extract_sources = wrapper.extract_sources
  console_session = WebConsole::REPLSession.create(
    binding: exception.bindings.first,
    binding_stack: exception.bindings
  )

**Comment by gsamokovarov** [comment]
@urmorae Can you test the latest master and see if the issue persist?

**Comment by urmorae** [comment]
Master is ok, it seems to be rather throughout rewrite. However, even in master one cannot turn of console popping up for localhost - even if config whitelist does not include 127.0.0.1

**Comment by gsamokovarov** [comment]
@urmorae Thanks for the feedback! I actually made this intentional, since I though most of the users are getting confused of why they can't get to the console once they whitelist a single IP. What's your use case of wanting to disable localhost?

**Comment by urmorae** [comment]
I have two rails developers working on the same project, one wants the console gone, one doesn't. Would the whitelist work, one could have different env with different config. Well, he does, but only since I monkey-patched v2.0.

**Comment by gsamokovarov** [comment]
You can still monkey patch `WebConsole::Request` in future `2.1`. Still not really sure if I should introduce a custom auth scheme just for this case. Will that work for you? Can I close the issue now?

**Comment by urmorae** [comment]
Sure, the monkey patch works for me.
