### ISSUE TITLE
Typing "c" causes segfault

### ISSUE THREAD

**Issue by frankh** [rails/web-console#111]
I suppose this is kind of a ruby bug more than web-console but anyway...

When typing just "c" in the console i get a segfault. Same thing happens with just "l" so I assume it's to do with debugger commands

Rails: 4.2.0
Web-console: master (3775fe0637d51ae8efb110fd9333dd1c86171e53)
Ruby: 2.1.3p242

partial trace:

    Started PUT "/console/repl_sessions/c17abb55e84469f3590b438f3042ae73" for 127.0.0.1 at 2015-02-27 17:04:04 +0000
    /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21: [BUG] Segmentation fault at 0x00000000000090
    ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin13.0]
    
    -- Crash Report log information --------------------------------------------
       See Crash Report log file under the one of following:
         * ~/Library/Logs/CrashReporter
         * /Library/Logs/CrashReporter
         * ~/Library/Logs/DiagnosticReports
         * /Library/Logs/DiagnosticReports
       for more details.
    
    -- Control frame information -----------------------------------------------
    c:0073 p:---- s:0391 e:000390 CFUNC  :open
    c:0072 p:0021 s:0388 E:000a90 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21
    c:0071 p:0046 s:0384 E:0025e0 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/web-console-3775fe0637d5/lib/web_console/integration/ [FINISH]
    c:0070 p:0005 s:0380 e:000379 EVAL   /Users/admin/git/my_app/app/views/layouts/application.html.haml:12 [FINISH]
    c:0069 p:---- s:0378 e:000377 CFUNC  :eval
    c:0068 p:0013 s:0374 e:000372 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/web-console-3775fe0637d5/lib/web_console/evaluator.rb
    c:0067 p:0011 s:0368 e:000367 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/web-console-3775fe0637d5/lib/web_console/session.rb:4
    c:0066 p:0062 s:0364 e:000362 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/web-console-3775fe0637d5/lib/web_console/middleware.r
    c:0065 p:0056 s:0354 e:000353 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/web-console-3775fe0637d5/lib/web_console/middleware.r
    c:0064 p:0098 s:0340 e:000339 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/m
    c:0063 p:0011 s:0332 e:000331 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptio
    c:0062 p:0098 s:0327 e:000326 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/m
    c:0061 p:0076 s:0319 E:0001f8 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38
    c:0060 p:0011 s:0312 e:000311 BLOCK  /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20
    c:0059 p:0007 s:0310 e:000309 BLOCK  /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68
    c:0058 p:0016 s:0308 e:000307 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26
    c:0057 p:0011 s:0303 e:000302 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68
    c:0056 p:0042 s:0299 e:000298 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20
    c:0055 p:0098 s:0294 e:000293 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/m
    c:0054 p:0032 s:0286 e:000285 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb
    c:0053 p:0098 s:0282 e:000281 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/m
    c:0052 p:0091 s:0274 e:000273 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22
    c:0051 p:0098 s:0269 e:000268 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/m
    c:0050 p:0024 s:0261 e:000260 METHOD /Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/runtime.rb:18

**Comment by gsamokovarov** [comment]
Yeah, my first instinct is to blame a C extension here. Is your Gemfile sensitive, can you post it here?

**Comment by frankh** [comment]
I'll post it on Monday. Possible candidates are new relic agent (as that's in the trace) or byebug (aka debugger, because c and l are debugger commands).

**Comment by frankh** [comment]
Here's the full Gemfile.lock

    GIT
      remote: https://github.com/FriendlyId/friendly_id.git
      revision: b5290a91aaa99847022ed9066712ef1d3192654e
      specs:        
        friendly_id (5.1.0)
          activerecord (>= 4.0.0)

    GIT
      remote: https://github.com/rails/web-console
      revision: 3775fe0637d51ae8efb110fd9333dd1c86171e53
      branch: master
      specs:
        web-console (2.0.0)
          activemodel (>= 4.0)
          binding_of_caller (>= 0.7.2)
          railties (>= 4.0)
          sprockets-rails (>= 2.0, < 4.0)

    GEM
      remote: https://rubygems.org/
      specs:
        CFPropertyList (2.3.0)
        actionmailer (4.2.0)
          actionpack (= 4.2.0)
          actionview (= 4.2.0)
          activejob (= 4.2.0)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 1.0, >= 1.0.5)
        actionpack (4.2.0)
          actionview (= 4.2.0)
          activesupport (= 4.2.0)
          rack (~> 1.6.0)
          rack-test (~> 0.6.2)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.1)
        actionview (4.2.0)
          activesupport (= 4.2.0)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.1)
        activejob (4.2.0)
          activesupport (= 4.2.0)
          globalid (>= 0.3.0)
        activemodel (4.2.0)
          activesupport (= 4.2.0)
          builder (~> 3.1)
        activerecord (4.2.0)
          activemodel (= 4.2.0)
          activesupport (= 4.2.0)
          arel (~> 6.0)
        activesupport (4.2.0)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        addressable (2.3.7)
        airbrake (4.1.0)
          builder
          multi_json
        arel (6.0.0)
        autoprefixer-rails (5.1.7)
          execjs
          json
        bazaar (0.0.2)
        binding_of_caller (0.7.2)
          debug_inspector (>= 0.0.1)
        blankslate (3.1.3)
        bootstrap-sass (3.3.3)
          autoprefixer-rails (>= 5.0.0.1)
          sass (>= 3.2.19)
        builder (3.2.2)
        byebug (3.5.1)
          columnize (~> 0.8)
          debugger-linecache (~> 1.2)
          slop (~> 3.6)
        capistrano (2.15.5)
          highline
          net-scp (>= 1.0.0)
          net-sftp (>= 2.0.0)
          net-ssh (>= 2.0.14)
          net-ssh-gateway (>= 1.1.0)
        capybara (2.4.4)
          mime-types (>= 1.16)
          nokogiri (>= 1.3.3)
          rack (>= 1.0.0)
          rack-test (>= 0.5.4)
          xpath (~> 2.0)
        capybara-mechanize (1.4.0)
          capybara (~> 2.4.4)
          mechanize (~> 2.7.0)
        carrierwave (0.10.0)
          activemodel (>= 3.2.0)
          activesupport (>= 3.2.0)
          json (>= 1.7)
          mime-types (>= 1.16)
        celluloid (0.16.0)
          timers (~> 4.0.0)
        childprocess (0.5.5)
          ffi (~> 1.0, >= 1.0.11)
        chronic_duration (0.10.6)
          numerizer (~> 0.1.1)
        chunky_png (1.3.4)
        cliver (0.3.2)
        cocoon (1.2.6)
        coderay (1.1.0)
        coffee-rails (4.1.0)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.0)
        coffee-script (2.3.0)
          coffee-script-source
          execjs
        coffee-script-source (1.9.1)
        columnize (0.9.0)
        compass (0.12.7)
          chunky_png (~> 1.2)
          fssm (>= 0.2.7)
          sass (~> 3.2.19)
        compass-rails (2.0.0)
          compass (>= 0.12.2)
        crack (0.4.2)
          safe_yaml (~> 1.0.0)
        cucumber (1.3.19)
          builder (>= 2.1.2)
          diff-lcs (>= 1.1.3)
          gherkin (~> 2.12)
          multi_json (>= 1.7.5, < 2.0)
          multi_test (>= 0.1.2)
        cucumber-rails (1.4.2)
          capybara (>= 1.1.2, < 3)
          cucumber (>= 1.3.8, < 2)
          mime-types (>= 1.16, < 3)
          nokogiri (~> 1.5)
          rails (>= 3, < 5)
        daemon_controller (1.2.0)
        daemons (1.1.9)
        dalli (2.7.2)
        database_cleaner (1.4.0)
        date_validator (0.7.1)
          activemodel
        debug_inspector (0.0.2)
        debugger-linecache (1.2.0)
        diff-lcs (1.2.5)
        docile (1.1.5)
        domain_name (0.5.23)
          unf (>= 0.0.5, < 1.0.0)
        elasticsearch (1.0.6)
          elasticsearch-api (= 1.0.6)
          elasticsearch-transport (= 1.0.6)
        elasticsearch-api (1.0.6)
          multi_json
        elasticsearch-model (0.1.6)
          activesupport (> 3)
          elasticsearch (> 0.4)
          hashie
        elasticsearch-rails (0.1.6)
        elasticsearch-transport (1.0.6)
          faraday
          multi_json
        erubis (2.7.0)
        eventmachine (1.0.7)
        excon (0.44.3)
        execjs (2.3.0)
        factory_girl (4.5.0)
          activesupport (>= 3.0.0)
        factory_girl_rails (4.5.0)
          factory_girl (~> 4.5.0)
          railties (>= 3.0.0)
        faraday (0.9.1)
          multipart-post (>= 1.2, < 3)
        ffi (1.9.6)
        fission (0.5.0)
          CFPropertyList (~> 2.2)
        flowdock (0.5.0)
          httparty (~> 0.7)
          multi_json
        fog (1.28.0)
          fog-atmos
          fog-aws (~> 0.0)
          fog-brightbox (~> 0.4)
          fog-core (~> 1.27, >= 1.27.3)
          fog-ecloud
          fog-json
          fog-profitbricks
          fog-radosgw (>= 0.0.2)
          fog-riakcs
          fog-sakuracloud (>= 0.0.4)
          fog-serverlove
          fog-softlayer
          fog-storm_on_demand
          fog-terremark
          fog-vmfusion
          fog-voxel
          fog-xml (~> 0.1.1)
          ipaddress (~> 0.5)
          nokogiri (~> 1.5, >= 1.5.11)
        fog-atmos (0.1.0)
          fog-core
          fog-xml
        fog-aws (0.1.1)
          fog-core (~> 1.27)
          fog-json (~> 1.0)
          fog-xml (~> 0.1)
          ipaddress (~> 0.8)
        fog-brightbox (0.7.1)
          fog-core (~> 1.22)
          fog-json
          inflecto (~> 0.0.2)
        fog-core (1.29.0)
          builder
          excon (~> 0.38)
          formatador (~> 0.2)
          mime-types
          net-scp (~> 1.1)
          net-ssh (>= 2.1.3)
        fog-ecloud (0.0.2)
          fog-core
          fog-xml
        fog-json (1.0.0)
          multi_json (~> 1.0)
        fog-profitbricks (0.0.1)
          fog-core
          fog-xml
          nokogiri
        fog-radosgw (0.0.3)
          fog-core (>= 1.21.0)
          fog-json
          fog-xml (>= 0.0.1)
        fog-riakcs (0.1.0)
          fog-core
          fog-json
          fog-xml
        fog-sakuracloud (1.0.0)
          fog-core
          fog-json
        fog-serverlove (0.1.1)
          fog-core
          fog-json
        fog-softlayer (0.4.1)
          fog-core
          fog-json
        fog-storm_on_demand (0.1.0)
          fog-core
          fog-json
        fog-terremark (0.0.4)
          fog-core
          fog-xml
        fog-vmfusion (0.0.1)
          fission
          fog-core
        fog-voxel (0.0.2)
          fog-core
          fog-xml
        fog-xml (0.1.1)
          fog-core
          nokogiri (~> 1.5, >= 1.5.11)
        font-awesome-rails (4.3.0.0)
          railties (>= 3.2, < 5.0)
        formatador (0.2.5)
        fssm (0.2.10)
        gherkin (2.12.2)
          multi_json (~> 1.3)
        globalid (0.3.3)
          activesupport (>= 4.1.0)
        green_monkey (0.2.2)
          chronic_duration
          haml (>= 3.1.0)
          mida_vocabulary (>= 0.2.2)
        guard (2.12.4)
          formatador (>= 0.2.4)
          listen (~> 2.7)
          lumberjack (~> 1.0)
          nenv (~> 0.1)
          notiffany (~> 0.0)
          pry (>= 0.9.12)
          shellany (~> 0.0)
          thor (>= 0.18.1)
        guard-compat (1.2.1)
        guard-cucumber (1.5.3)
          cucumber (>= 1.3.0)
          guard (>= 2.0.0)
          guard-compat (~> 1.0)
          nenv (~> 0.1)
        guard-rails (0.7.1)
          guard (~> 2.11)
          guard-compat (~> 1.0)
        guard-rspec (4.5.0)
          guard (~> 2.1)
          guard-compat (~> 1.1)
          rspec (>= 2.99.0, < 4.0)
        guard-spork (2.1.0)
          childprocess (>= 0.2.3)
          guard (~> 2.0)
          guard-compat (~> 1.0)
          spork (>= 0.8.4)
        haml (4.0.6)
          tilt
        haml-rails (0.8.2)
          actionpack (>= 4.0.1)
          activesupport (>= 4.0.1)
          haml (>= 3.1, < 5.0)
          html2haml (>= 1.0.1)
          railties (>= 4.0.1)
        hashie (3.4.0)
        highline (1.7.1)
        hike (1.2.3)
        hitimes (1.2.2)
        html2haml (2.0.0)
          erubis (~> 2.7.0)
          haml (~> 4.0.0)
          nokogiri (~> 1.6.0)
          ruby_parser (~> 3.5)
        http-cookie (1.0.2)
          domain_name (~> 0.5)
        httparty (0.13.3)
          json (~> 1.8)
          multi_xml (>= 0.5.2)
        i18n (0.7.0)
        inflecto (0.0.2)
        ipaddress (0.8.0)
        jquery-rails (4.0.3)
          rails-dom-testing (~> 1.0)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        jquery-rails-cdn (1.0.3)
          jquery-rails
        jquery-timepicker-rails (1.4.3)
          railties (>= 3.1.0)
        js-routes (1.0.0)
          railties (>= 3.2)
          sprockets-rails
        json (1.8.2)
        jwt (1.3.0)
        kaminari (0.16.3)
          actionpack (>= 3.0.0)
          activesupport (>= 3.0.0)
        kgio (2.9.3)
        launchy (2.4.3)
          addressable (~> 2.3)
        libv8 (3.16.14.7)
        listen (2.8.5)
          celluloid (>= 0.15.2)
          rb-fsevent (>= 0.9.3)
          rb-inotify (>= 0.9)
        loofah (2.0.1)
          nokogiri (>= 1.5.9)
        lumberjack (1.0.9)
        mail (2.6.3)
          mime-types (>= 1.16, < 3)
        mechanize (2.7.3)
          domain_name (~> 0.5, >= 0.5.1)
          http-cookie (~> 1.0)
          mime-types (~> 2.0)
          net-http-digest_auth (~> 1.1, >= 1.1.1)
          net-http-persistent (~> 2.5, >= 2.5.2)
          nokogiri (~> 1.4)
          ntlm-http (~> 0.1, >= 0.1.1)
          webrobots (>= 0.0.9, < 0.2)
        method_source (0.8.2)
        microdata (0.0.3)
          nokogiri
        mida_vocabulary (0.2.2)
          blankslate (~> 3.1)
        mime-types (2.4.3)
        mini_magick (4.1.0)
        mini_portile (0.6.2)
        minitest (5.5.1)
        multi_json (1.10.1)
        multi_test (0.1.2)
        multi_xml (0.5.5)
        multipart-post (2.0.0)
        mysql2 (0.3.18)
        nenv (0.2.0)
        net-http-digest_auth (1.4)
        net-http-persistent (2.9.4)
        net-scp (1.2.1)
          net-ssh (>= 2.6.5)
        net-sftp (2.1.2)
          net-ssh (>= 2.6.5)
        net-ssh (2.9.2)
        net-ssh-gateway (1.2.0)
          net-ssh (>= 2.6.5)
        netrc (0.10.3)
        newrelic_rpm (3.10.0.279)
        nokogiri (1.6.6.2)
          mini_portile (~> 0.6.0)
        notiffany (0.0.6)
          nenv (~> 0.1)
          shellany (~> 0.0)
        ntlm-http (0.1.1)
        numerizer (0.1.1)
        oauth2 (1.0.0)
          faraday (>= 0.8, < 0.10)
          jwt (~> 1.0)
          multi_json (~> 1.3)
          multi_xml (~> 0.5)
          rack (~> 1.2)
        oj (2.11.5)
        passenger (4.0.59)
          daemon_controller (>= 1.2.0)
          rack
          rake (>= 0.8.1)
        poltergeist (1.6.0)
          capybara (~> 2.1)
          cliver (~> 0.3.1)
          multi_json (~> 1.0)
          websocket-driver (>= 0.2.0)
        pry (0.10.1)
          coderay (~> 1.1.0)
          method_source (~> 0.8.1)
          slop (~> 3.4)
        rack (1.6.0)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (4.2.0)
          actionmailer (= 4.2.0)
          actionpack (= 4.2.0)
          actionview (= 4.2.0)
          activejob (= 4.2.0)
          activemodel (= 4.2.0)
          activerecord (= 4.2.0)
          activesupport (= 4.2.0)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.2.0)
          sprockets-rails
        rails-deprecated_sanitizer (1.0.3)
          activesupport (>= 4.2.0.alpha)
        rails-dom-testing (1.0.5)
          activesupport (>= 4.2.0.beta, < 5.0)
          nokogiri (~> 1.6.0)
          rails-deprecated_sanitizer (>= 1.0.1)
        rails-html-sanitizer (1.0.1)
          loofah (~> 2.0)
        rails-i18n (4.0.4)
          i18n (~> 0.6)
          railties (~> 4.0)
        railties (4.2.0)
          actionpack (= 4.2.0)
          activesupport (= 4.2.0)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        raindrops (0.13.0)
        rake (10.4.2)
        rb-fsevent (0.9.4)
        rb-inotify (0.9.5)
          ffi (>= 0.5.0)
        redcarpet (3.2.2)
        ref (1.0.5)
        rest-client (1.7.3)
          mime-types (>= 1.16, < 3.0)
          netrc (~> 0.7)
        ri_cal (0.8.8)
        rspec (3.2.0)
          rspec-core (~> 3.2.0)
          rspec-expectations (~> 3.2.0)
          rspec-mocks (~> 3.2.0)
        rspec-core (3.2.1)
          rspec-support (~> 3.2.0)
        rspec-expectations (3.2.0)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (~> 3.2.0)
        rspec-mocks (3.2.1)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (~> 3.2.0)
        rspec-rails (3.2.1)
          actionpack (>= 3.0, < 4.3)
          activesupport (>= 3.0, < 4.3)
          railties (>= 3.0, < 4.3)
          rspec-core (~> 3.2.0)
          rspec-expectations (~> 3.2.0)
          rspec-mocks (~> 3.2.0)
          rspec-support (~> 3.2.0)
        rspec-support (3.2.2)
        ruby_parser (3.6.4)
          sexp_processor (~> 4.1)
        rubyzip (1.1.7)
        safe_yaml (1.0.4)
        sass (3.2.19)
        sass-rails (4.0.4)
          railties (>= 4.0.0, < 5.0)
          sass (~> 3.2.2)
          sprockets (~> 2.8, < 2.12)
          sprockets-rails (~> 2.0)
        selenium-webdriver (2.44.0)
          childprocess (~> 0.5)
          multi_json (~> 1.0)
          rubyzip (~> 1.0)
          websocket (~> 1.0)
        sexp_processor (4.4.5)
        shellany (0.0.1)
        show_me_the_cookies (2.6.0)
          capybara (~> 2.0)
        simple_form (3.1.0)
          actionpack (~> 4.0)
          activemodel (~> 4.0)
        simplecov (0.9.2)
          docile (~> 1.1.0)
          multi_json (~> 1.0)
          simplecov-html (~> 0.9.0)
        simplecov-html (0.9.0)
        simplecov-rcov (0.2.3)
          simplecov (>= 0.4.1)
        slop (3.6.0)
        spork (0.9.2)
        spring (1.3.3)
        sprockets (2.11.3)
          hike (~> 1.2)
          multi_json (~> 1.0)
          rack (~> 1.0)
          tilt (~> 1.1, != 1.3.0)
        sprockets-rails (2.1.3)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (~> 2.8)
        therubyracer (0.12.1)
          libv8 (~> 3.16.14.0)
          ref
        thin (1.6.3)
          daemons (~> 1.0, >= 1.0.9)
          eventmachine (~> 1.0)
          rack (~> 1.0)
        thor (0.19.1)
        thread_safe (0.3.4)
        tilt (1.4.1)
        timers (4.0.1)
          hitimes
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (2.7.0)
          execjs (>= 0.3.0)
          json (>= 1.8.0)
        unf (0.1.4)
          unf_ext
        unf_ext (0.0.6)
        unicorn (4.8.3)
          kgio (~> 2.6)
          rack
          raindrops (~> 0.7)
        vcr (2.9.3)
        webmock (1.20.4)
          addressable (>= 2.3.6)
          crack (>= 0.3.2)
        webrobots (0.1.1)
        websocket (1.2.1)
        websocket-driver (0.5.3)
          websocket-extensions (>= 0.1.0)
        websocket-extensions (0.1.2)
        xpath (2.0.0)
          nokogiri (~> 1.3)
        zeroclipboard-rails (0.1.0)
          railties (>= 3.1)

    PLATFORMS
      ruby

    DEPENDENCIES
      airbrake
      autoprefixer-rails
      bazaar
      blankslate
      bootstrap-sass
      byebug
      capistrano
      capybara-mechanize
      carrierwave
      chronic_duration
      cocoon
      coffee-rails
      compass-rails
      cucumber-rails
      database_cleaner
      date_validator
      elasticsearch-model
      elasticsearch-rails
      excon
      fog
      font-awesome-rails
      friendly_id!
      green_monkey
      guard-cucumber
      guard-rails
      guard-rspec
      guard-spork
      haml
      haml-rails
      has_properties!
      jquery-rails-cdn
      jquery-timepicker-rails
      js-routes
      json
      kaminari
      launchy
      microdata
      mini_magick
      mysql2
      newrelic_rpm
      oj
      passenger
      poltergeist
      rails (~> 4.2.0)
      rails-i18n
      redcarpet
      ri_cal
      rspec-rails
      sass-rails (~> 4.0.3)
      selenium-webdriver
      show_me_the_cookies
      simple_form
      simplecov
      simplecov-rcov
      spring
      therubyracer
      thin
      uglifier
      unicorn
      vcr
      web-console!
      webmock
      zeroclipboard-rails (~> 0.1.0)

**Comment by frankh** [comment]
also, it seems it doesn't segfault in the console on the error page, only when inserting in my template using ```= console```

**Comment by gsamokovarov** [comment]
@frankh, does it crash on any `NameError` or just on `c`, `l`? E.g. if you type `i_am_sure_there_is_no_such_local_var_or_method` does it crash as well?

**Comment by frankh** [comment]
I thought it didn't crash with every nameerror because I tested "asd" and that didn't crash. 

Turns out it was just a coincidence, and almost everything crashes every time (including "asd")

**Comment by gsamokovarov** [comment]
@frankh if you can reproduce it in a view console, can you try to boil down a reproducible testing app with the same `Gemfile{,.lock}`. It would be of great help to me investigating, because I still can't get it to crash on me.

**Comment by frankh** [comment]
I've managed to create a reproduction repo, but it seems very flakey (sometimes I could reproduce, sometimes I can't)

It's at ```https://github.com/frankh/web-console-issue-111```

Steps to reproduce:

  1. ```git clone https://github.com/frankh/web-console-issue-111```
  2. ```cd web-console-issue-111```
  3. ```bundle```
  4. ```bundle exec rails s```
  5. open new chrome incognito window (make sure all incognito windows are closed first)
  6. go to localhost:3000/?console=1
  7. In console spam like this for a while (usually takes no more than ~30 errors)
![screen shot 2015-03-02 at 15 23 39](https://cloud.githubusercontent.com/assets/2088870/6443665/2b616314-c0f0-11e4-9fb7-a905b9967db7.png)
  8. You should get a seg fault!


It sometimes works first time, mostly I have to add some more gems into the gemfile (or remove, run, add again), then try again.

Sorry I couldn't make the test case easier - seems the smaller I made it the less the error happened

**Comment by gsamokovarov** [comment]
Hey, @frankh, I am able to reproduce the problem now. Thank you so much!

**Comment by gsamokovarov** [comment]
I'm closing this PR as stale. It's been awhile, it the issue still persists with the newer rubies, please feel free to reopen it.
