### ISSUE TITLE
hide logs 

### ISSUE THREAD

**Issue by rstormsf** [rails/web-console#126]
Is it possible just to hide those logs:

```
Rendered /Users/gangam/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.1.2/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.4ms)
```

**Comment by gsamokovarov** [comment]
We're using `ActionView` for rendering of the Web Console markup and it instruments those events that get logged during rendering. We can probably hack something around it, but I like the transparency it gives.
