### ISSUE TITLE
web-console and Rack::Deflater

### ISSUE THREAD

**Issue by dreyks** [rails/web-console#128]
When using `Rack::Deflater` the console doesn't appear. Obviously cause it is trying to attach itself to a gzipped body.

The solution is to include `Rack::Deflater` as early as possible
```ruby
#config/application.rb
class Application < Rails::Application
  config.middleware.insert(0, Rack::Deflater)
end
```

probably should be noted in FAQ section

**Comment by gsamokovarov** [comment]
Thanks for the heads up! You can open a PR for the [README section](https://github.com/rails/web-console#faq).

**Comment by dreyks** [comment]
Ok, will do

**Comment by gsamokovarov** [comment]
:+1:

**Comment by dreyks** [comment]
rails/web-console#130

**Comment by gsamokovarov** [comment]
Thanks!
