### ISSUE TITLE
undefined method `web_console' for #<Rails::Application::configuration

### ISSUE THREAD

**Issue by frenesim** [rails/web-console#133]
I have this on my rails configuration 
config.web_console.whitelisted_ips = '10.11.50.22'
which works as supposed, but i can't run test unless I comment it.

So:
shell> rspec
I get:
undefined method `web_console' for #<Rails::Application::Configuration:0x00000002305190> (NoMethodError)

I opened an issue on rspec as well.

**Comment by yuki24** [comment]
I guess you just have to move `config.web_console. whitelisted_ips = ...` to `config/environments/development.rb` from `config/application.rb`.

**Comment by gsamokovarov** [comment]
Thanks @yuki24. I will try to hint setting the configuration in the environment specific files in the docs.

**Comment by frenesim** [comment]
Thanks yuki24 your guess is accurate. With this I learn that each configuration line belongs to a place and I should take the time to think about where to place them.

**Comment by arogachev** [comment]
In my case, I forgot to specify `RAILS_ENV=production` for `db:migrate` and `db:seed` commands.

**Comment by JMasschelein** [comment]
@yuki24 This indeed worked. Thx !
