### ISSUE TITLE
'method_missing': undefined method when using guard gem running tests

### ISSUE THREAD

**Issue by lustremedia** [rails/web-console#143]
When running guard I get following error:

gems/railties-4.2.2/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `web_console' for #<Rails::Application::Configuration:0xba8024b4> (NoMethodError)

This is with latest 2.1.3 GEM. 
I saw #33 but the issue mentioned there and the resolve seems to be a newer version.

**Comment by lustremedia** [comment]
Ah I just now saw #133 let me see if that is the issue

**Comment by gsamokovarov** [comment]
Keep the configuration in `config/environments/development.rb` and `web-console` only in the `development` group (not even the test one). This should fix it for you.
