### ISSUE TITLE
web-console 2.2.0 causes "Web Console is activated in the test environment"

### ISSUE THREAD

**Issue by jcoyne** [rails/web-console#150]
The default Gemfile for rails 4.2.3 has web-console in the test group. 

See https://github.com/rails/rails/pull/20319#issuecomment-120487468

**Comment by jcoyne** [comment]
See https://github.com/rails/rails/blob/v4.2.3/railties/lib/rails/generators/rails/app/templates/Gemfile#L24-L41

**Comment by gsamokovarov** [comment]
This is intentional, but maybe the change hasn't been backported to the 4-2-stable branch. I'll tweak the readme and try to push for the backport. Thanks for the report!

**Comment by gsamokovarov** [comment]
The backport [did](https://github.com/rails/rails/pull/20319#issuecomment-120491827) happened.
