### ISSUE TITLE
The old 'cannot render console' revamping

### ISSUE THREAD

**Issue by pdipietro** [rails/web-console#164]
Hi all,

After installing the `gem 'web-console', '~> 2.0'` I got an error stating `cannot render console from ....`
So I searched the web and added a `config.web_console.whitelisted_ips = '192.168.10.10'` in the development.rb.

Now the error become a little bit more intriguing:

    Started GET "/assets/cloudinary/jquery.ui.widget.self.js?body=1" for 192.168.10.10 at 2015-09-15 08:55:04 +0200
    Cannot render console from 192.168.10.10! Allowed networks: 192.168.10.10, 127.0.0.0/127.255.255.255, ::1

where 192.168.10.10 is my reverse proxy address .......

**Comment by gsamokovarov** [comment]
When did you install it? Is that the last released `web-console` version?

**Comment by pdipietro** [comment]
Well, because it is written in any of the doc sheets of your site .... in any version .....

Now I'll try to install the 2.2.1, which seems to be the latest one released.

I'll let you know if this will solve the problem.

```
group :development do
  gem 'web-console', '~> 2.0'
end
```

**Comment by gsamokovarov** [comment]
This should be fixed in `3.0.0`. Allow all of the IP's you see web-console blocking in the logs.
