### ISSUE TITLE
Whitelisted but still cannot render console in Docker

### ISSUE THREAD

**Issue by brunze** [rails/web-console#166]
Is there any reason why web console wouldn't work on Rails app running inside a Docker container? I've whitelisted the source IP address but it isn't working:

```
app_1 | Started GET "/cats" for 172.17.1.88 at 2015-09-29 15:17:05 +0000
app_1 | Cannot render console from 172.17.1.88! Allowed networks: 172.17.1.88, 127.0.0.0/127.255.255.255, ::1
```

Same thing happens if I whitelist the whole address block:

```
app_1 | Started GET "/cats" for 172.17.1.94 at 2015-09-29 15:19:10 +0000
app_1 | Cannot render console from 172.17.1.94! Allowed networks: 172.16.0.0/172.31.255.255, 127.0.0.0/127.255.255.255, ::1
```

I'm using web-console 2.2.1. Dockerfile:
```
FROM ruby:2.2

RUN apt-get update -qq && apt-get install -yqq build-essential vim git libpq-dev postgresql-client && rm -rf /var/lib/apt/lists/*
RUN wget -qO- https://deb.nodesource.com/setup_0.12 | bash - 2>&1 > /dev/null && apt-get -yqq install nodejs && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY Gemfile* ./
RUN bundle install

EXPOSE 8080
CMD ["bundle", "exec", "unicorn", "-c", "docker/configs/unicorn.rb"]
```

**Comment by gsamokovarov** [comment]
This is a dup of #164. Sorry for the inconvenience, will try to track down the problem and release a new version with a fix as soon as possible.

**Comment by brunze** [comment]
Oops! My bad. I'll close this one and track the original issue. Thanks!

**Comment by gsamokovarov** [comment]
Hey @brunze, sorry to bother you again, but can you help me get a small, stripped-down and reproducible application out of it? I have set up a VM and I can't seem to get the issue there as the whitelisting allows it.

Any context will be useful to me: where did you setup the config. What other gems do you use? OS, Ruby, anything you can think of. All of this can be of great help to me.

**Comment by brunze** [comment]
Yes, absolutely. I'll get back to you with this asap.

**Comment by brunze** [comment]
Hi @gsamokovarov! I was in the process of narrowing down my Docker setup when I figured it out:

I have Nginx and Unicorn on separate containers. The web console worked if I sent the requests directly to Unicorn. But If I sent the requests through Nginx it would have the problem stated above. 

The `172.17.*.*` address is Nginx's IP as seen from Unicorn, inside the VM. However, my IP outside the VM was in `192.168.*.*`. On a hunch, I decided to try `config.web_console.whitelisted_ips = ['172.16.0.0/12', '192.168.0.0/16']` and it worked! :smile: Not sure why it has to be that way though.

But if you need I can give you the Docker stop for testing.

**Comment by gsamokovarov** [comment]
Thanks for the input and glad that it worked for you! :smile: I would like to go down this rabbit hole, if there is something sensitive about and you can't post it here or in a public gist, you can mail them to me at the-same-handle-as-in-github@gmail.com.

**Comment by brunze** [comment]
All right, here's the setup I used: https://github.com/brunze/wctest
