### ISSUE TITLE
With  ruby 2.3.0 I got undefined symbol: rb_data_typed_object_alloc 

### ISSUE THREAD

**Issue by aboltart** [rails/web-console#175]
I installed latest **ruby 2.3.0**

and updated web-console to **3.0.0** 

But I got following error from debug_inspector which is web-console dependency

```
debug_inspector-0.0.2/lib/debug_inspector.so: undefined symbol: rb_data_typed_object_alloc
```

**Comment by gsamokovarov** [comment]
When do you get that? Have you recompiled all of the dependencies? You sure you are building the dependency with the proper Ruby headers?

**Comment by aboltart** [comment]
False alarm. After removing all installed gems, and re-bunle all again all was fine.

**Comment by gsamokovarov** [comment]
:+1:
