### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by Svashta** [rails/web-console#186]
Whenever web_console is rendered i am getting ERR_CONTENT_DECODING_FAILED inside Chrome. Haven't tried other browsers yet.

In rails log everything seems fine.

**Comment by gsamokovarov** [comment]
Can you give me a bit more context? Do you have any gzip/deflate middlewares across the middleware stack?

**Comment by Svashta** [comment]
I am using Rack::Deflater.
After commenting it out console works.

Is this normal? I mean, can't I use both?

Thx!

**Comment by gsamokovarov** [comment]
See this section of the [README](https://github.com/rails/web-console#why-does-console-only-appear-on-error-pages-but-not-when-i-call-it).
