### ISSUE TITLE
Web console NoMethodError exception

### ISSUE THREAD

**Issue by slbug** [rails/web-console#188]
<pre>
NoMethodError: undefined method `[]' for nil:NilClass
  from .rvm/gems/ruby-2.3.0@tt/gems/web-console-3.1.1/lib/web_console/middleware.rb:58:in `acceptable_content_type?'
</pre>

middlewares output:

- use Raven::Rack
- use Rack::Sendfile
- use ActionDispatch::Static
- use Rack::Lock
- use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007ffe23f67650>
- use Rack::Runtime
- use Rack::MethodOverride
- use ActionDispatch::RequestId
- use Rails::Rack::Logger
- use ActionDispatch::ShowExceptions
- use WebConsole::Middleware
- use ActionDispatch::DebugExceptions
- use ActionDispatch::RemoteIp
- use ActionDispatch::Reloader
- use ActionDispatch::Callbacks
- use ActiveRecord::Migration::CheckPending
- use ActiveRecord::ConnectionAdapters::ConnectionManagement
- use ActiveRecord::QueryCache
- use ActionDispatch::Cookies
- use ActionDispatch::Session::ActiveRecordStore
- use ActionDispatch::Flash
- use ActionDispatch::ParamsParser
- use Remotipart::Middleware
- use Rack::Head
- use Rack::ConditionalGet
- use Rack::ETag
- use Warden::Manager
- run TT::Application.routes

By some reason on this line `status, headers, body = call_app(env)` we have headers and body set as `nil`

**Comment by gsamokovarov** [comment]
Can you give me a bit more context? What Ruby/Rails version are you using. When is this error happening?

**Comment by gsamokovarov** [comment]
Could `use Raven::Rack` be the cause?

**Comment by slbug** [comment]
Rails 4.2.5.1
Ruby 2.3.0

And yes, removing Raven::Rack resolves issue

**Comment by gsamokovarov** [comment]
Can you give me the raven-ruby version as well?

**Comment by gsamokovarov** [comment]
(Closing, as it doesn't seem to be Web Console related, will investigate the issue on the third party.)

**Comment by slbug** [comment]
sentry-raven-0.15.5
