### ISSUE TITLE
Production impact ?

### ISSUE THREAD

**Issue by alkuzad** [rails/web-console#190]
I was considering wrapping up authorization in addition to IP restriction to be able to use this on production. On develop better_errors is enough in most scenarios but on prod the visibility of all generated variables could be useful.

Is this solution light enough to use it on prod server ? I'm not interested in safety issues with that - I understand the implications of console access. Still with correct per user authorization setup it should be possible to restrict it enough to be production ready.

**Comment by gsamokovarov** [comment]
I would strongly recommend against that, but if you really wanna do it, you can.

Make sure to set the `config.web_console.development_only = false` flag.
