### ISSUE TITLE
Support Ruby 2.1

### ISSUE THREAD

**Issue by paulmenzel** [rails/web-console#191]
Is it intended that Ruby 2.2.2 is required? Would it be possible to support Ruby >= 2.1?

```
$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [i686-linux]
$ bundle upgrade web-console
[…]

Gem::InstallError: web-console requires Ruby version >= 2.2.2.
An error occurred while installing web-console (3.1.1), and Bundler cannot continue.
Make sure that `gem install web-console -v '3.1.1'` succeeds before bundling.
```

**Comment by gsamokovarov** [comment]
Web Console 3 follows the Ruby requirements set by Rails 5. You can try the latest release of the [2.x](https://github.com/rails/web-console/releases/tag/v2.3.0) series.

**Comment by paulmenzel** [comment]
Could you please update the README then, documented what version or branch is for what Ruby on Rails version?

**Comment by gsamokovarov** [comment]
That, I did. I tried to be more specific about the version requirement.
