### ISSUE TITLE
Update requirements in Gem specification

### ISSUE THREAD

**Issue by paulmenzel** [rails/web-console#192]
If I understand the answer #191 correctly, Web Console 3.x is for Ruby on Rails 5. If that’s the case, the Ruby on Rails version requirement should be updated in Gem specification `.gemspec`.

```
  s.required_ruby_version = '>= 2.2.2'

  rails_version = ">= 4.2"
```

**Comment by gsamokovarov** [comment]
I intentionally allowed that for the first `3.x` versions, without trying to offer any _explicit_ support for it, hoping for an easier transition to `3.x`. When Rails 5 is out of beta, I'll release a web-console version that explicitly depends on it.

**Comment by connorshea** [comment]
@gsamokovarov now that Rails 5 is out do you still intend to depend on it?

**Comment by gsamokovarov** [comment]
Yeah, I don't support Ruby 1.9.3 anymore pushed for some artificial 4.2 support while Rails 5 was still in beta. Release `3.3.1` that bumped the gemspec Rails requirement to 5.0.0 and above.

🍻
