### ISSUE TITLE
Replace development_only option with a whitelist

### ISSUE THREAD

**Issue by swalkinshaw** [rails/web-console#209]
A Rails app I work on has a `local` environment which is basically a copy of `development`.

I just ran into the warning/error about `development_only` and realized an explicit whitelist may be an improvement over it.

Before:

``` ruby
config.web_console.development_only = false
```

After:

``` ruby
config.web_console.allowed_environments = %i(development local) # default would be %i(development)
```

Right now it's either `development` only or **all** environments which isn't great for security.

If there's any interest in this, I'd be happy to do a PR.

**Comment by gsamokovarov** [comment]
I'm a bit hesitant about it as people can use it to safelist `staging` or `production` and we're always advocating against it. But hey, it can be done right now as well, so why not give a bit more control. Will try to get it in a future release.
