### ISSUE TITLE
Capitalisation of first letter in the IOS simulator

### ISSUE THREAD

**Issue by obromios** [rails/web-console#212]
When a ruby on rails page is being viewed in a webview in the xcode ios simulator, if the rails code hits and exception, then web-console opens as usual. This pretty neat, except that the first letter of anything you type into the console is capitalised.  This makes it hard to type any commands into the console, unless they start with a capital letter e.g. a class name.

Is this possible/worth fixing, or is there a simple work around? I have tried hitting shift and capslock and neither helps.

**Comment by gsamokovarov** [comment]
Will look it up.
