### ISSUE TITLE
Console not rendering on remote server

### ISSUE THREAD

**Issue by manavortex** [rails/web-console#218]
Hey there,

my issue is as follows: 

`INFO  Rails : Cannot render console from 172.20.10.254! Allowed networks: 172.20.10.254, 127.0.0.0/127.255.255.255, ::1`

Help? :D

**Comment by gsamokovarov** [comment]
Which `web-console` version are you running on? You may need to whitelist both `192.168` and `172.` for docker containers or vms.

**Comment by manavortex** [comment]
Hello there, 

I'm using web-console (3.3.0) and Rails 4.2.7. 

Funny thing is, today I'm logged in remotely, and suddenly it works. I'll be in the other network again on monday, will keep you posted from there!

Thank you for your help!

**Comment by gsamokovarov** [comment]
Whitelist both of the networks it's in. We check all of the networks to be sure the IP isn't from a spoofed` X-Forwarded-For`.

Hope this works for you! I'm gonna close it for now, feel free to reopen if you still can't access the console.
