### ISSUE TITLE
web-console interfering with live reloading of code?

### ISSUE THREAD

**Issue by raghubetina** [rails/web-console#229]
Hi all,

In some cases, it appears that using the web-console interferes with live reloading of code.

[Here's a brand new app that demonstrates the issue.](https://github.com/raghubetina/web-console-reloading#web-console-live-reloading-bug-demo) (Rails 5.0.1, Ruby 2.3.3) It has only one action, which has a web-console embedded at the bottom of its view.

If I modify some code and refresh *without* using the web-console at all, it reloads fine.

If I use the console at all before modifying code, then live reloading is broken until my next server restart.

The issue is intermittent; in my testing, it happens about 75% of the time, but I haven't been able to pin down exact steps to reproduce 100% of the time yet. Hopefully the steps I laid out in the README above work for you.

I have tried (without any real rationale, more or less shots in the dark):

 - Reducing Puma threads to 1.
 - Switching to Webrick.
 - Ensuring that `config.file_watcher = ActiveSupport::EventedFileUpdateChecker` is present in `development.rb`.

But none of them seem to help.

Is this expected behavior? I admit my use case is pretty unusual (I wanted to embed a web-console in a tutorial).

Thank you!

**Comment by gsamokovarov** [comment]
This is an interesting issue, we haven't stumbled upon it until now. Let me investigate a bit and I'll get back to you. Thanks for the reproducible application!

**Comment by raghubetina** [comment]
I forgot to mention that I also tried removing turbolinks, and was still able to reproduce the issue after doing so.

Thanks for taking a look!

**Comment by raghubetina** [comment]
Hi all, I was just wondering if anyone else is experiencing this issue? It is still occurring for us.

**Comment by eimhin** [comment]
I'm experience this issue as well.
