### ISSUE TITLE
Disable render blocking exept whitelist ips

### ISSUE THREAD

**Issue by likelazyeyes** [rails/web-console#231]
This is need to accept all ips to render web-console. Because we can not know which ip is used as socket on cloud development machines. Ex: codenenvy, cloud9! Because each "rails s" the socket ip is changing. I need to allow all ip addresses in development environtment.

**Comment by gsamokovarov** [comment]
You can whitelist a whole network for cases like this, see the README:

---

> If you want to whitelist the whole private network, you can do:

```ruby
Rails.application.configure do
  config.web_console.whitelisted_ips = '192.168.0.0/16'
end
```

**Comment by likelazyeyes** [comment]
But it is not enough. Cloud ides are changing ip when restarted. And there no standart for calculate an ip range
