### ISSUE TITLE
run_load_hooks is running too early to be useful

### ISSUE THREAD

**Issue by betesh** [rails/web-console#235]
`Activesupport.run_load_hook` runs [here](https://github.com/rails/web-console/blob/2bf42d0b2d5e928b7907cfa8c42505b2cd12a3b2/lib/web_console.rb), which is loaded by `Bundler.require`.  So it actually runs before the `before_configuration` hook and before any initializers.

This is inconsistent with any other Rails components, which (when initializers make use on `ActiveSupport.on_load` correctly) so not run their load hooks until after the initializers in `Rails::Application::Finisher` run, or potentially even later.

So I suspect that this was not the intention and that there's a better place to run WebConsole's load hooks, but I'm not sure where.  I can submit a PR if someone can answer that question for me.

**Comment by gsamokovarov** [comment]
The AS hook has been there the [very beginning](https://github.com/gsamokovarov/web-console/blob/v0.1.0/lib/web_console.rb#L6) of the project, but I don't think the hook is useful. My sloppy [GitHub search](https://github.com/search?utf8=%E2%9C%93&q=ActiveSupport.on_load%28%3Aweb_console%29+extension%3Arb&type=Code) doesn't show anything public using it, but it could be possible for something private to be using it, (although I highly doubt it). I think it's fine to remove it. @rafaelfranca do you see any problem with that?

**Comment by rafaelfranca** [comment]
I think it make sense to remove. I don't see why it was being defined.

**Comment by betesh** [comment]
Closed in favor of PR #236
