### ISSUE TITLE
Whitelist IP is incorrectly matched

### ISSUE THREAD

**Issue by leoamigood** [rails/web-console#238]
# version 2.3
  config.web_console.whitelisted_ips = %w(127.0.0.1 172.0.0.0/8)
  config.web_console.development_only = false

Cannot render console from 172.56.17.176! Allowed networks: 127.0.0.1, 172.0.0.0/172.255.255.255, 127.0.0.0/127.255.255.255, ::1

**Comment by gsamokovarov** [comment]
Are you using `docker` or `vagrant`/`virtualbox`? You may wanna whitelist `192.168.0.0/16`, because to get to the console, you still need to go through that network. You may wanna upgrade to `web-console 3.x` series, a lot of issues have been fleshed out from `2.3`.

**Comment by leoamigood** [comment]
I am using Heroku. Locally i've tested it with Docker, had no issues.
Also, it seems like 3.x is not compatible with rails 4.2 that I am running.

**Comment by leoamigood** [comment]
once i allowed 0.0.0.0/0 it actually worked. 
So the question is: how come message about render console is showing wrong IP? (i guess there is more to it)

**Comment by gsamokovarov** [comment]
See #171. You can install Web Console up to `3.3.0` on Rails 4.2, so I would suggest you to do that.
