### ISSUE TITLE
web-console is swallowing up errors

### ISSUE THREAD

**Issue by purinkle** [rails/web-console#239]
Since updating web-console to 3.5.0, when an error is raised in the Development environment, we get the "Oops! Something went wrong" message in the browser. We were expecting to see some sort of stack trace. When looking in the development logs there is no relevant message either. I have gone through the commits added by the release and it seems to be caused by https://github.com/rails/web-console/commit/bf82820ce92d9e00376bb19818b97964dc6698ae

**Comment by gsamokovarov** [comment]
Thank you for the report! Do you have a small reproducible app, so I can dig in a bit further?

**Comment by gsamokovarov** [comment]
We have tried to make the errors more verbose when web-console crashes in https://github.com/rails/web-console/pull/181, I'll take a look on that front as well.

**Comment by gsamokovarov** [comment]
@purinkle Can you try `master` and see if that solves your problem?

**Comment by spdawson** [comment]
I can confirm that pointing to `master` resolves the issue in my application

**Comment by gsamokovarov** [comment]
I have released `3.5.1`. Please reopen the issue if you still run into problems.
