### ISSUE TITLE
Console presence interferes with instance variables

### ISSUE THREAD

**Issue by matthaliski** [rails/web-console#245]
Okay, this is an odd one. And I'm not even really sure how to go about describing it so I created this gif. (Sorry for the quality. Didn't want a 100mb gif)

![example](https://github.com/matthaliski/foo/blob/master/web-console-example.gif?raw=true)

**Summary** - swapping an instance variable value works *without* the console present, but becomes very inconsistent *with* the console present.

**Longer Version**

This is a vanilla Rails 5.1 install which you can find [here](https://github.com/matthaliski/foo). Steps to get to the issue:

1. Create new Rails 5.1 project
2. Kill/remove Turbolinks (just in case)
3. Boot the Rails server with Webrick so we eliminate potential threading issues
4. Use scaffold to create a Post example.
5. Add a @foo instance variable to the edit action and print it out in the view.
6. Toggle the @foo value and watch it change upon page refresh
7. Invoke a `console` in the edit action
8. Continue toggling the @foo variable with very inconsistent results. Sometimes I have to hammer refresh several times or completely navigate away and come back.

Any ideas? As with most of the things I do it's probably something stupid that I'm overlooking, but I got tripped up in a non-trivial app that was spitting back values that didn't make sense.

Thanks in advance.

**Comment by gsamokovarov** [comment]
Hey, thank you so much for the detailed report! I'll take a look and get back to you with what may be causing this behaviour.

**Comment by matthaliski** [comment]
Thanks Genadi. I appreciate the help. It's a weird one.

**Comment by raghubetina** [comment]
I believe this is the same issue as #229. Weird one indeed!

**Comment by matthaliski** [comment]
@raghubetina - yup, sounds identical.

**Comment by raghubetina** [comment]
To add to the mystery: it doesn't appear to be limited to instance variables.

Here's an example where all I do in a brand new Rails app is print a value to the server log, and after one or two refreshes, changing the value to be printed does not have any effect.

Even weirder, the `object_id` of the controller instance _is_ changing:

![reloading](https://user-images.githubusercontent.com/811217/32409480-634c1610-c17a-11e7-9081-dfd38ca083b4.gif)

Here's the application that I reproduced with:

https://github.com/raghubetina/weird-console
