### ISSUE TITLE
Lightning talk about the web-console project in RubyKaigi 2017 (Japan)

### ISSUE THREAD

**Issue by sh19910711** [rails/web-console#247]
Hi all, # cc: @dhh 

Just a minor issue, it seems that my proposal for [RubyKaigi 2017 LT CFP](https://cfp.rubykaigi.org/events/2017LT) has been accepted, and I would talk about my GSoC projects for the web-console in the lightning talk session (e.g., browser extensions and auto completion feature). So yeah, it would be comming a chance that we can introduce the ***rails/web-console*** project to the Ruby communities.

I think this issue would be able to close #121 fow now. (but it's not meaning that it stops creating the browser extensions, I just want to take a break for my GSoC. I would create another issue if it is ready).

@gsamokovarov Genadi, I'm very sorry for my blank time. I haven't got enough time to contribute this project yet. I'm a bit busy now, but I will be back to contribute this project as soon as possible in anyway, because I love the Web Console and the Rails.

Thanks :-)

**Comment by gsamokovarov** [comment]
This is awesome! I value your contributions a lot and you have helped `web-console` development tremendously. 🙇🏼 

Good luck with the talk. ❤️
