### ISSUE TITLE
Unable to run in production mode on heroku server

### ISSUE THREAD

**Issue by djdon11** [rails/web-console#266]
I have an application which is deployed on heroku and for some reasons I want to enable web console there.
This is the setup details:
In Gemfile
ruby '2.3.0'
rails 4.2
web console 3.3.0

in Application.rb
 config.web_console.development_only = false
 config.web_console.whitelisted_ips = [MY IP ADDRESS]

When I tried to run on local with production env it is working fine even when I add other machine IP address(connected via LAN) and try to access the web app installed on my machine it seems working(when I remove their IP address then it is not showing any console on web pages) so I can say config.web_console.whiltelisted_ips configuration is working.

but when I add my external IP address(public IP address) in whitelisted ips and push to heroku then I am unable to see web console there.

always sees some random ips there in console like this:

Cannot render console from 10.63.146.94! Allowed networks: 103.15.67.226, 174.129.192.200, 127.0.0.0/127.255.255.255, ::1

and this '10.63.146.94!' changed always.

I am not sure where I am missing something or there are some error on gem?

**Comment by gsamokovarov** [comment]
Did you figure it out? I'd strongly urge you to reconsider the production `web-console` usage.

The error is because the IP request is proxied to the heroku dyno, and we do a few security checks on-top to make sure we can trust the address. You may need to whitelist a different network than the one you expect.
