### ISSUE TITLE
web console not showing up on error page

### ISSUE THREAD

**Issue by justinbkay** [rails/web-console#268]
I have a app that has been upgraded from rails 1.2 all the way to rails 5.2 over the years.  I have included the web-console gem in the project, but it doesn't  display on the error pages.  

Gemfile:
...
gem 'web-console', '>= 3.3.0'
gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
...

Any help would be appreciated.

**Comment by justinbkay** [comment]
If you use Vagrant for development, you'll need to add a ip whitelist for console to work properly.  Look for the console cannot be rendered error in your server log output.

**Comment by gsamokovarov** [comment]
Glad it worked out for you!
