### ISSUE TITLE
Puts doesn't work in web_console

### ISSUE THREAD

**Issue by jrbapna** [rails/web-console#271]
![image](https://user-images.githubusercontent.com/641899/47934803-c96f7200-deae-11e8-83b4-bceabbdc2847.png)

Is there a workaround?

**Comment by gsamokovarov** [comment]
Puts prints the text to the standard output, e.g. the terminal which runs the development rails server. We don't capture it, because it's global for the program, which can be problematic some development servers. You can see the puts output on the rails server terminal tab or window.

**Comment by jrbapna** [comment]
Thanks. I do however need this to work for my use case, and the product owner is persistent. Do you have a suggestion on how I could go about capturing puts from web_console on a forked branch?
