### ISSUE TITLE
Can't type single or double quotes?

### ISSUE THREAD

**Issue by andreynering** [rails/web-console#281]
macOS Mojave 10.14.5
Keyboard Layout: US International
Rails 5.0.7.2
Webconsole 3.7.0
Tried on both Firefox (Developer Edition) 68.0b11 and Chrome 75.0.3770.100

I really can't type `'` or `"` on the console. Hitting the quote key does absolutely nothing. There's no JavaScript errors on the browser console.

**Comment by acastro2** [comment]
Why was this closed, still doesn't work for me, what is the fix?
