### ISSUE TITLE
Release 4.0.0 please?

### ISSUE THREAD

**Issue by alexagranov** [rails/web-console#282]
There's currently only a `v4.0.0` tag and so plain `gem :web-console` is picking up the latest `3.7.0` release which doesn't use the latest Permissions/etc.

**Comment by alexagranov** [comment]
nvm, I see `4.0.0` is meant to be coupled with Rails 6.

**Comment by gsamokovarov** [comment]
Yes, we'll release 4.0.1 or 4.1.0 a bit before the final Rails 6 release.
