### ISSUE TITLE
Console won't render on production

### ISSUE THREAD

**Issue by cassiopagnoncelli** [rails/web-console#284]
I've followed the basic setup to have console working on production.

Added to `application.rb`

```
config.web_console.whiny_requests = false
config.web_console.development_only = false
```

and wrote an authenticated & authorized view to show `<%= console =>`.

Turns out it just won't render.

**Comment by cassiopagnoncelli** [comment]
Any news here?

I was seeing an old post advocating for `config.web_console.allowed_environments` listing allowed environments. My intention is to use in production for a super admin user.

**Comment by gsamokovarov** [comment]
Sorry for the late response @cassiopagnoncelli. This question comes often, but running `web-console` on production is a security nightmare and not something we want to support or endorse.  We have made it explicitly hard to enable in production.

**Comment by cassiopagnoncelli** [comment]
@gsamokovarov I understand that, it's quite clear. Thing is, I want to avoid forking it to make it possible in prod.

**Comment by gsamokovarov** [comment]
https://github.com/rails/web-console/blob/be84e6471c33bbbea17f6dfc9e5ed3c7c7c4bb57/lib/web_console/railtie.rb#L29
