### ISSUE TITLE
How do you clear the console?

### ISSUE THREAD

**Issue by petebytes** [rails/web-console#286]
On a regular console I can use Ctrl + L or Command + K to clear the console.
Is there a way to accomplish the same using web-console?

Thanks

**Comment by gsamokovarov** [comment]
Sorry, there is no current way to clear the console.

**Comment by petebytes** [comment]
No problem - still very useful :)

**Comment by gsamokovarov** [comment]
Our frontend is a bit rusty at this point, but if you want to add clear screen support we're always open for contributions! ❤️

**Comment by TSMMark** [comment]
Would you still accept a PR for clear behavior, and if so, any tips?
