### ISSUE TITLE
So,  if you execute "exit" or something and need to restart the console, what's the procedure?

### ISSUE THREAD

**Issue by spemmons** [rails/web-console#287]
I could not find this in the docs. The console is great, but it's not clear how to  restart it if needed. Any suggestions?

**Comment by gsamokovarov** [comment]
This is a good question! It runs pure ruby code, so if you say `Kernel.exit` (or simply `exit`), it will terminate the server. 😅

What do you mean by restart of the console? Do you have any suggestions how we may communicate this?

**Comment by spemmons** [comment]
ah... curious... we are running puma in a docker instance and the console appears to be a separate process because puma is still working to server the page we're using for the <% console %> statement ... so i'm guessing that whatever triggered the initial execution of the console could be used to instantiate a new process

**Comment by gsamokovarov** [comment]
Yeah, refresh the page or run the development server with a single process so you know you'll always hit the memory of the process you want to debug.
