### ISSUE TITLE
Readonly Access

### ISSUE THREAD

**Issue by malayhm** [rails/web-console#294]
I think if we want to prevent users to access console without write access, web-console can not be used.

Any plans to add a read-only configuration option so that the end-user can't update anything?

**Comment by gsamokovarov** [comment]
This will be a whole new project, the whole idea of Web Console is to allow you to debug your program and this includes the execution of arbitrary Ruby code. Web Console is not suitable for production use and we explicitly made it hard for it to run in non-development environments.
