### ISSUE TITLE
ANSI escape codes not rendering correctly

### ISSUE THREAD

**Issue by etherz10** [rails/web-console#295]
Currently running v3.7.0 on Rails 5.2.4.3 & Ruby 2.5.8 and using Chrome 84.0.4147.105

![image](https://user-images.githubusercontent.com/1347813/89178630-f3732e00-d585-11ea-905b-bf87d140df7b.png)

Any suggestions on how to fix this? It's nothing major but does just make things a bit harder to read.

**Comment by gsamokovarov** [comment]
Hey, web-console is no longer a real terminal and this is why we don't render escape codes. That said, I can probably strip them, though. Is this coming from the output of a shell-out?

**Comment by etherz10** [comment]
> Is this coming from the output of a shell-out?

Yea, would you be able to create a release with this fix for Rails 5 also?
