### ISSUE TITLE
CurrentAttributes gets reset for web-console requests

### ISSUE THREAD

**Issue by excid3** [rails/web-console#307]
I wasn't sure if I should report this in Rails or web-console. Let me know if I should open this in Rails instead. 

If we have a Rails app with Current.user assigned and try to print `Current.user` in web-console on an error page, it will return `nil`

<img width="799" alt="Screen Shot 2020-12-31 at 4 35 24 PM" src="https://user-images.githubusercontent.com/67093/103427365-344b8f00-4b86-11eb-9158-5dead55c4a97.png">

The expected behavior in this example is that `Current.user` should return `1`.

I assume this is happening because Current is thread-local and gets reset each request. I'm not sure how to solve this, but if anyone has some pointers I'd be happy to take a stab at a PR. 👍

**Comment by Willardgmoore** [comment]
Thanks for the help figuring out that I wasn't going crazy and that this was a real error.

**Comment by excid3** [comment]
CurrentAttributes is reset here in Rails:  https://github.com/rails/rails/blob/12ce3e7723651f442e89fdc2d8be06ad00d2f228/activesupport/lib/active_support/railtie.rb#L21-L24

@kaspth saw you were in the commit for those lines. Any ideas on a solution for this?

**Comment by gsamokovarov** [comment]
This can be tricky, because Web Console evaluates the code *after* the request has been done, and the `Current` state has been reset.

**Comment by gsamokovarov** [comment]
I'd be closing this. Web Console is post-mortem debugger and by the time we debug, that global `Current` state has been reset.

**Comment by adrianthedev** [comment]
I'm running into the same issue. @excid3 did you somewhat fix/hack web-console or current to use it like that after all?

**Comment by excid3** [comment]
@adrianthedev If you cache the value in an instance variable, you can still access it.

**Comment by adrianthedev** [comment]
I thought about that.
You mean like this?

```ruby
class Current < ActiveSupport::CurrentAttributes
  attribute :user

  def user=(value)
    super
    @user = value
  end

  def user
    super || @user
  end
end
```

**Comment by kaspth** [comment]
Here's a potential take where WebConsole, listens and captures the attributes, and then has a hook that it can re-set the attributes during a block:

```ruby
module WebConsole::CurrentAttributesSift
  def inherited(klass)
    klass.before_reset { WebConsole::CurrentAttributes.capture klass }
  end
end

ActiveSupport::CurrentAttributes.extend WebConsole::CurrentAttributesSift

class WebConsole::CurrentAttributes
  @attributes = {}

  def self.capture(klass)
    @attributes[klass] = klass.attributes
  end

  def self.materialize_during(&block)
    old_attributes = @attributes.each_key.index_with(&:attributes)
  
    @attributes.each { |klass, attributes| klass.attributes = attributes }
    yield
  ensure
    old_attributes.each { |klass, attributes| klass.attributes = attributes }
    @attributes.clear
  end
end
```

Not sure how dangerous this would be though!

**Comment by kaspth** [comment]
Or maybe something like this?

```ruby
class Current < ActiveSupport::CurrentAttributes
  if Rails.env.development?
    singleton_class.attr_accessor :previous_attributes
    before_reset { self.previous_attributes = attributes }
  end
end
```

**Comment by excid3** [comment]
I like the `previous_attributes` idea @kaspth 👍
