### ISSUE TITLE
web-console complains about being active in the test environment when tailwindcss-rails gets update

### ISSUE THREAD

**Issue by pupeno** [rails/web-console#326]
I'll continue debugging this but I thought you may know what's going on or be able to give me some pointers as to what to look for. My project is open source, so I can point you out to the pull request that's causing web-console to stop working: 

https://github.com/flexpointtech/repeater_world/pull/321/files

It updates two gems, nokogiri and tailwindcss-rails. I upgraded nokogiri on its own and it didn't seem to be the culprit, so it must be tailwindcss-rails but I have no idea how yet.

What happens is that when I run `rake spec` I get this error:

```
Web Console is activated in the test environment. This is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

If you still want to run it in the test environment (and know
what you are doing), put this in your Rails application
configuration:

    config.web_console.development_only = false
```

For more details:

```
pupeno@a:~/repeater_world$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
pupeno@a:~/repeater_world$ rake spec
/home/pupeno/.rbenv/versions/3.1.2/bin/ruby -I/home/pupeno/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.2/lib:/home/pupeno/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-support-3.12.1/lib /home/pupeno/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.2/exe/rspec --pattern
 spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 32190
.....^C

pupeno@a:~/repeater_world$ git checkout dependabot/bundler/tailwindcss-rails-2.0.30
Switched to branch 'dependabot/bundler/tailwindcss-rails-2.0.30'
Your branch is up to date with 'origin/dependabot/bundler/tailwindcss-rails-2.0.30'.
pupeno@a:~/repeater_world$ rake spec
Web Console is activated in the test environment. This is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

If you still want to run it in the test environment (and know
what you are doing), put this in your Rails application
configuration:

    config.web_console.development_only = false
```

Any ideas?

**Comment by rafaelfranca** [comment]
This is an expected message. I'm surprised it never showed before, but it should have. If the Rails is booted in any environment and webconsole isn't defined in the gemfile only in the development group, you should see that message. Make sure you do what the error message is giving you.

**Comment by pupeno** [comment]
webconsole is defined only in the development group: https://github.com/flexpointtech/repeater_world/blob/ba14d185d52f74cab91e9ac68da3460e4b8fe271/Gemfile#L67

**Comment by pupeno** [comment]
Am I misunderstanding something here? It's asking me to define web-console only in development when I already have it only in development.

Also, the tailwindcss-rails devs seem to agree something is going on: https://github.com/rails/tailwindcss-rails/issues/275

**Comment by rafaelfranca** [comment]
Something is requiring `web-console.rb` in the test environment and isn't this gem. You could try to debug by pointing to a local copy of this gem and raising on `lib/web-console.rb`

**Comment by rafaelfranca** [comment]
Maybe it is RubyMine that is forcing this gem to be required when running tests?

**Comment by pupeno** [comment]
I'm running them on the console by running `rake spec`, so I don't think it's RubyMine causing the issue.

**Comment by pupeno** [comment]
Could webconsole somehow generate a stack trace to find the culprit? This bug is now happening when I upgrade other things and it's blocking me from upgrading (to the point where I'm just thinking of removing webconsole until I figure it out).

**Comment by gsamokovarov** [comment]
You can remove `web-console`. This is the first time we get such report, there should be something wrong with your config but I cannot figure it out at a glance.
