### ISSUE TITLE
undefined method `web_console'

### ISSUE THREAD

**Issue by kandadaboggu** [rails/web-console#33]
I get the following error when ever I try to use the web_console config parameters in `application.rb` OR `development.rb` OR in a separate initializer file.

```
NoMethodError: undefined method `web_console' for #<Rails::Application::Configuration:0x000000061694b8>
    from /home/user1/.rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.4/lib/rails/railtie/configuration.rb:95:in `method_missing'
    from (irb):3
    from /home/user1/.rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
    from /home/user1/.rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
```

The web-console shows up in exception pages and if I add the `<%= console %>` in views. I can't seem to access the console by going to `/console`  URL.

**Comment by kovenko** [comment]
Gemfile
group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end


$ bundle show web-console
/home/kvb/.rvm/gems/ruby-2.3.0/gems/web-console-2.3.0


$ bundle exec unicorn -E production
I, [2016-03-11T10:32:54.329011 #13450]  INFO -- : listening on addr=0.0.0.0:8080 fd=9
I, [2016-03-11T10:32:54.329252 #13450]  INFO -- : worker=0 spawning...
I, [2016-03-11T10:32:54.330528 #13450]  INFO -- : master process ready
I, [2016-03-11T10:32:54.332694 #13453]  INFO -- : worker=0 spawned pid=13453
I, [2016-03-11T10:32:54.333136 #13453]  INFO -- : Refreshing Gem list
E, [2016-03-11T10:32:56.858299 #13453] ERROR -- : undefined method `web_console' for #<Rails::Application::Configuration:0x0000000498dd80>
Did you mean?  console (NoMethodError)
/home/kvb/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.1/lib/rails/railtie/configuration.rb:95:in `method_missing'
/home/kvb/Ruby/oauth2/config/application.rb:26:in `<class:Application>'
/home/kvb/Ruby/oauth2/config/application.rb:10:in `<module:Oauth2>'
/home/kvb/Ruby/oauth2/config/application.rb:9:in `<top (required)>'
/home/kvb/Ruby/oauth2/config/environment.rb:2:in `require'
/home/kvb/Ruby/oauth2/config/environment.rb:2:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `eval'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `block in builder'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `build_app!'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:617:in `init_worker_process'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:639:in `worker_loop'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
/home/kvb/.rvm/gems/ruby-2.3.0/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
/home/kvb/.rvm/gems/ruby-2.3.0/bin/unicorn:23:in `load'
/home/kvb/.rvm/gems/ruby-2.3.0/bin/unicorn:23:in `<main>'
/home/kvb/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/kvb/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
E, [2016-03-11T10:32:56.884067 #13450] ERROR -- : reaped #<Process::Status: pid 13453 exit 1> worker=0
I, [2016-03-11T10:32:56.884302 #13450]  INFO -- : worker=0 spawning...
I, [2016-03-11T10:32:56.886392 #13457]  INFO -- : worker=0 spawned pid=13457
I, [2016-03-11T10:32:56.886916 #13457]  INFO -- : Refreshing Gem list
^CI, [2016-03-11T10:32:58.100837 #13450]  INFO -- : reaped #<Process::Status: pid 13457 exit 0> worker=0
I, [2016-03-11T10:32:58.101194 #13450]  INFO -- : master complete

**Comment by aleksandra-stolyar** [comment]
the same..

**Comment by gsamokovarov** [comment]
Are you guys keeping the web-console configuration in `config/application.rb`? If you do, the web-console gem is loaded only in development and the settings won't be present by it's railtie.

It's better if you keep the configuration in `config/environments/development.rb`.

**Comment by aleksandra-stolyar** [comment]
@gsamokovarov ha! Thanks, worked!!

**Comment by kovenko** [comment]
Gemfile
group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

Error present if app/config/application.rb include string like
config.web_console.whitelisted_ips = ['127.0.0.1','92.24.195.2','71.24.168.15','71.24.168.1']

**Comment by brlo** [comment]
@kovenko if you connect gem like so (default):

```ruby
group :development do
  gem 'web-console', '~> 2.0'
end
```
you will get web-console only at development environment.

**Comment by parikshit223933** [comment]
This happeded with me when i ran
```
bundle install --without development test ci
```
I fixed it with
```
bundle install --with development test ci
```
