### ISSUE TITLE
Permissions are not working when runs thru ngrok

### ISSUE THREAD

**Issue by alexey** [rails/web-console#333]
### Reproduce:

**Setup:**
Ruby 3.2.0
Rails 7.0.4
No `spring`

**Steps:**
* ngrok, run app with tunnel,
* configuration as follows 
```ruby
module MyApp
  class Application < Rails::Application
      config.web_console.allowed_ips = %w(::/0 x.x.x.x xxxx:c701:73c1:9e00:7c06:xxxx:xxxx:9652)
      # or config.web_console.permissions = "x.x.x.x" with any of above 
```
* Add somewhere in the controller:
```ruby
def show
  @item = Item.find id
  console
end
```
* Run app, visit url thru tunnel
* `09:53:22 web.1      | Cannot render console from xxxx:c701:73c1:9e00:7c06:xxxx:xxxx:9652! Allowed networks: 0.0.0.0/255.255.255.255, 127.0.0.0/127.255.255.255, ::1`

### Investigation:

Also tried to set each of the above ips - my public IP, ip of the ngrok host, my IP6, and the IP from the error "Cannot render console from..", but nothing helped to see the console behind the tunnel. 
I looked through the code, and it's obvious how it works, so I guess it's somehow related to ngrok tunneling/proxy.

I think adding some configuration like `config.web_console.allow_from_all = true` might help with this matter.

Have I missed something that helps with that or I can create a PR for that ?

**Comment by rafaelfranca** [comment]
Doesn't setting `config.web_console.allowed_ips = %w(::/0 0.0.0.0/0)` work?

**Comment by alexey** [comment]
> Doesn't setting `config.web_console.allowed_ips = %w(::/0 0.0.0.0/0)` work?

No, the same - `Cannot render console from..`

**Comment by rafaelfranca** [comment]
Can you take a look why?

If you look at the code that check if it is allowed it use `IPAdrr#include?` and that returns true for any IP when using that range.

```ruby
>> x = IPAddr.new("0.0.0.0/0")
=> #<IPAddr: IPv4:0.0.0.0/0.0.0.0>
>> x.include?("1.2.3.4")
=> true
```

**Comment by alexey** [comment]
hi @rafaelfranca  ! 

after a deeper investigation, I've found that development. rb in that app already included `config.web_console.permissions = "0.0.0.0/0"` in the middle of nowhere. changing it to `config.web_console.allowed_ips = %w(::0/0)`

we can close this PR unless you think it may be useful
