### ISSUE TITLE
Brackets and Braces don't work for me, I have a Spanish keyboard

### ISSUE THREAD

**Issue by pastuxso** [rails/web-console#40]

**Comment by rthauvin** [comment]
Same for me. I have an AZERTY french keyboard layout : all special characters normally triggered with the [ALT] keys (ie.: #{[|`\^@]}€¤) don"t work at all. Any workaround until resolved? (except copying/pasting the characters from elsewhere). Thanks.

**Comment by ryandao** [comment]
Interesting, I never thought about that. The current console considers ALT (and CTRL) key combinations as non-renderable as specified in the logic here https://github.com/rails/web-console/blob/master/lib/web_console/templates/console.js.erb#L322. 

I don't have any workaround at the moment. @gsamokovarov maybe we need to re-think the current key press approach? A hidden input element should solve this problem.

**Comment by gsamokovarov** [comment]
@ryandao, if you wanna take a shot at that, please go ahead.

**Comment by Serveurperso** [comment]
Same problem here please help

**Comment by augustosamame** [comment]
Same problem here. Forced to copy paste brackets and braces until fix

**Comment by bsylvain** [comment]
I use an azerty keyboard, and 'alt gr' modifier to use chars such as ~#{[|` does not work in chrome 54. However, it works in Firefox 49.

**Comment by gsamokovarov** [comment]
Please feel free to chime in and I'll reopen if this issue is still present in the upcoming `3.6.0` release.
