### ISSUE TITLE
Spring::MissingApplication when in a Rails engine

### ISSUE THREAD

**Issue by davidmles** [rails/web-console#48]
I'm trying out web-console in a Rails engine.

The error page and the `console` command work well, showing up the web console.

But when auto-mounting and going to the `/console` URL, an error shows up: Spring::MissingApplication

I have added `config.web_console.automount = true` to `/test/dummy/config/environments/development.rb`

I have grabbed a screenshot: 
![screenshot](https://cloud.githubusercontent.com/assets/1402642/4232244/71bdcc9a-399a-11e4-9449-5e4f992a33ea.png)

**Comment by gsamokovarov** [comment]
Support for `/console` was removed in 2.0 stable, because of feature creep.
