### ISSUE TITLE
Webconsole  2.0.0.beta3 Immediate SEGFAULT

### ISSUE THREAD

**Issue by Pugio** [rails/web-console#50]
Rails 4.1.2rc2. Install the gem, embed the <%= console %>, and try to enter any line into the resulting console box (e.g "a = 1"). The server immediately crashes.

This gist: https://gist.github.com/Pugio/475117839ac8cfb58352 has both the terminal output and the full crash log. Happy to help debug.

**Comment by gsamokovarov** [comment]
Closing this one as stalled. Please reopen if it happens on `3.0.0`.
