### ISSUE TITLE
Investigate the ability to close a console once rendered on a page

### ISSUE THREAD

**Issue by gsamokovarov** [rails/web-console#82]
People have showed an interest to be able to close a console, once rendered from a view or a controller action. Let's prototype an UI. I would like to avoid a key combination, so it doesn't collide with the currently running application.

**Comment by rubyconvict** [comment]
+1, I love web-console when it is needed, but I hate it when it trashes my view all the time, please add some toggle functionality, because IP filter is poor man's option, consider full-stack devs or frontend guys, we all work on localhost in development.

**Comment by gsamokovarov** [comment]
Should be closed by #140. A new release will follow soon.
