### ISSUE TITLE
Can't evaluate anything from the shell - 500 or 404 errors

### ISSUE THREAD

**Issue by rosenfeld** [rails/web-console#90]
First I got 500 errors with no stacktrace and then I added 0.0.0.0 to whitelisted_ips (it seems to be detecting the request from IPV6 ::1) and the error changed to 404 and now I get a stacktrace:

```
Started PUT "/console/repl_sessions/b106fd6a16f9b78a51dab5b770f9d13d" for ::1 at 2014-12-22 17:32:57 -0200

ActionController::RoutingError (No route matches [PUT] "/console/repl_sessions/b106fd6a16f9b78a51dab5b770f9d13d"):
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:22:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.9.1) lib/puma/server.rb:490:in `handle_request'
  puma (2.9.1) lib/puma/server.rb:361:in `process_client'
  puma (2.9.1) lib/puma/server.rb:254:in `block in run'
  puma (2.9.1) lib/puma/thread_pool.rb:92:in `call'
  puma (2.9.1) lib/puma/thread_pool.rb:92:in `block in spawn_thread'


  Rendered /home/rodrigo/.rvm/gems/ruby-2.1.5/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.text.erb (0.4ms)
  Rendered /home/rodrigo/.rvm/gems/ruby-2.1.5/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/routing_error.text.erb (3.0ms)
```

Any ideas?

**Comment by zdavis** [comment]
I'm experiencing this behavior as well—what's strange is that it's intermittent. Maybe 1 out of 10 requests that the console makes succeed, while the other 9 return a 500 error. I'm using nginx + unicorn. There's no indication of what's wrong in the Rails logs or in nginx's logs.

**Comment by gsamokovarov** [comment]
@zdavis the evaluation sessions are preserved in memory. If you have multiple unicorn workers, they are separate processes. When nginx balances them, you can hit a worker that doesn't have the session. I will try to document that behaviour better.

**Comment by zdavis** [comment]
Oh, that makes sense—I do have multiple unicorn workers running in development. Thanks for the explanation!

**Comment by gsamokovarov** [comment]
@zdavis, @rosenfeld Can you guys try out the latest master and see if the problem still persist? Your feedback would be of great help.

**Comment by rosenfeld** [comment]
Now I only see the static error page with details but no input to evaluate anything. I changed the bind address to 0.0.0.0 to be sure... Any ideas?

**Comment by gsamokovarov** [comment]
@rosenfeld have you checked whether the IP is whitelisted?

**Comment by rosenfeld** [comment]
I added 0.0.0.0. Isn't it enough?

**Comment by gsamokovarov** [comment]
@rosenfeld So you have something like `config.web_console.whitelisted_ips = %w( 0.0.0.0 )` in the config? If so, this will whitelist addresses coming _only_ from the 0.0.0.0 IP. All those whitelists are actually implemented with `IPAddr` and it supports network masks to whitelist whole networks.

If you wanna catch all the IPv4 addresses, you have to do: `config.web_console.whitelisted_ips = %w( 0.0.0.0/0 )`. You may be hitting it from an IPv6 address to, so you can whitelisted every IPv6 address with `config.web_console.whitelisted_ips = %w( ::/0 )`

Just for the test, to enable access everywhere, you can use:

```ruby
# This will whitelist all IPv4 and IPv6 addresses. Please, only
# run tests with that configuration, its a huge security hole.
config.web_console.whitelisted_ips = %w( 0.0.0.0/0 ::/0 )
```

**Comment by rosenfeld** [comment]
Hi, I tried this setting but the result was the same.

I've also tried `<%= console %>` in the view and got no output. Any ideas?

**Comment by rosenfeld** [comment]
This is how I included the gem in the Gemfile:

```ruby
gem 'web-console', github: 'rails/web-console'
```

**Comment by gsamokovarov** [comment]
@rosenfeld can you give me some more info for the environment, so I can try and reproduce it locally. Ruby and Rails. Development server version and maybe versions of other gems introducing middleware.

**Comment by rosenfeld** [comment]
I'll try to find some time to create some sample application. I can't send you our Gemfile and Gemfile.lock because some gems are internal ones and are not available on rubygems. Right now I'm a bit busy but I'll try to create another project with most of the gems and see if I can replicate the issue... We're using Rails 4.2.0 (Railties only actually as we don't use ActiveRecord).

**Comment by rosenfeld** [comment]
Ok, I just created a new Rails app and I think I could reproduce the issue. It works until I add "puma" to the Gemfile. If you can't reproduce please let me know and I'll publish the sample project.

**Comment by gsamokovarov** [comment]
Thanks @rosenfeld for helping me. I think fixed the Puma rendering in #100.

**Comment by rosenfeld** [comment]
Hi, yes! Thank you very much :) It's fixed on master. Sorry for the delay, I was practicing bandolim and didn't see the messages before :P

**Comment by IceSaTwo** [comment]
@rosenfeld @gsamokovarov 
was the fix puma or was it by whitelisting the addresses?
I'm finding that I 'Cannot render console from' an IPv6 address, so i think it's a similar issue.
