### ISSUE TITLE
Return key not working

### ISSUE THREAD

**Issue by pmontrasio** [rails/web-console#96]
I created an empty Rails 4.2 application using rails new.
I access http://localhost:3000/a to get a 404 error and open the console.
I can type anything but nothing happens when I press the return key. It's completely ignored and the cursor keeps staying on the same line.
I tested that with Firefox 34.0 and Opera 26.0 on Ubuntu 12.04.5, Ruby 2.1.0 and Ruby 2.2.0.
Another possibly related strange behaviour is that no console appears if I add ```console``` into a controller (rails g controller welcome, action index) or ```<%= console %>``` in a view (welcome/index.html.erb).

**Comment by ttosch** [comment]
Same issue about the return key on Chromium 41.0.2249.0 (Plugins: ABP, Ghostery), Ubuntu 14.04, ruby 2.1.5p273, rails 4.2.0. `<%= console %>` not tested.

**Comment by bdewater** [comment]
I'm having the same problem. If I go to an error page (say http://local.dev:8080/foo/bar/) I get the following error every time I type something in the web console and hit enter:
`PUT http://cauth.dev.dmtw.nl:8080/foo/bar/console/repl_sessions/a4ec05340db9379b5c3753198cb7f524 404 (not found)`
So the enter key does work...

**Comment by pmontrasio** [comment]
Thank you for the feedback. I checked and I have the same error. In my case the hash (?) at the end is different (not unexpected) and the error sent by Rails is:

```
Routing Error

No route matches [PUT] "/foo/console/repl_sessions/5218610e593a63f5041fdbc3583f2a25"

Rails.root: /home/me/test

Framework Trace
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:22:in `middleware_call'
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.0) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/application.rb:164:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
rack (1.6.0) lib/rack/content_length.rb:15:in `call'
rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

Full Trace
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:22:in `middleware_call'
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.0) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/application.rb:164:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
rack (1.6.0) lib/rack/content_length.rb:15:in `call'
rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

  Rendered /home/me/.rvm/gems/ruby-2.2.0@rails42/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.text.erb (0.3ms)
  Rendered /home/me/.rvm/gems/ruby-2.2.0@rails42/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/routing_error.text.erb (4.3ms)
```

**Comment by gsamokovarov** [comment]
This seems to be a common problem, thank you guys for confirming it. I will try to make it reproducible and fix it as soon as possible.

**Comment by hackeron** [comment]
Same issue here, cannot press enter/return :(

**Comment by gsamokovarov** [comment]
@pmontrasio, @ttosch, @bdewater and @hackeron can you guys try out the latest master and see if the problem still persists?

The easiest way to do that is putting the following line in your `Gemfile`:

```
gem 'web-console', github: 'rails/web-console'
```

Your feedback would be of great help.

**Comment by ttosch** [comment]
Works for me now, thanks very much! This is awesome, web console is so much fun :+1:

**Comment by pmontrasio** [comment]
It works now, but only with 

    gem 'web-console', '2.0.0.beta4'

If I put this in the Gemfile the console doesn't appear at all

    gem 'web-console', github: 'rails/web-console'

and that seems a further regression over the original bug report. However it's still doing something because if I put ```console``` in a controller action and ```<%= console %>``` I get a ```WebConsole::DoubleRenderError``` error.

Anyway, beta4 seems to have fixed it. Thanks!

**Comment by ttosch** [comment]
@pmontrasio, for me the console didn't appear as well, but it turned out that I was not accessing on localhost and had forgotten to specify `config.web_console.whitelisted_ips = %w( xx.xx.xx.xx )` in my environment.

**Comment by rctneil** [comment]
I've been having these same issues since Rails 4.2 was released. I can ONLY get it working with: `gem web-console', '2.0.0.beta4'

**Comment by gsamokovarov** [comment]
@rctneil, can you try master and see if the issues persist?

**Comment by rctneil** [comment]
@gsamokovarov Nope, when using : gem 'web-console', github: 'rails/web-console' it fails to even show the console.

**Comment by bdewater** [comment]
We've since switched our apps over from a Ubuntu VM with Passenger setup to CoreOS VM + Dockers with Puma setup. After pulling in master (at 38b1540), the console was at first not shown. After setting [config.web_console.whitelisted_ips](https://github.com/rails/web-console#configweb_consolewhitelisted_ips) to allow 10.0.0.0/8 (env dump on error page had REMOTE_ADDR: "10.1.42.1"), web console is shown and works :smile:

**Comment by drewswaycool** [comment]
curious why this is closed if it's not fixed?

**Comment by gsamokovarov** [comment]
I do believe its fixed. @drewswaycool Can you try the latest master and see if it still persists for you? If the console isn't shown because of whitelisting issue, a message on the Rails log will be displayed to help you what's going on.

If the issue is really still global, I will reopen it.

**Comment by drewswaycool** [comment]
Using master I frequently get "Session unavailable" though the return key does seem to work now.

**Comment by gsamokovarov** [comment]
@drewswaycool Do you happen to run on a multi-process server like unicorn?

**Comment by drewswaycool** [comment]
Yeah actually.. did I miss something in the docs?

**Comment by gsamokovarov** [comment]
Because we persist the REPL session in memory, if you run it in unicorn with multiple processes, you are likely to hit a worker, which doesn't have the session in its own process memory, so multi worker environments aren't the best bet. Yeah, this isn't mentioned in the docs and we really lack good docs at the moment. Any contributions are greatly appreciated on that side :)

What I can do is hint what is happening in the error message, so it gives more context than plain `Session unavailable`. 

A solution to your problem is to run unicorn with a single worker process in development.

**Comment by panaak** [comment]
also having issues in rails 4.2. for me it only works with:

gem 'web-console', '2.0.0.beta4'

2.0: gives routing error
github master: does not show the console at all

**Comment by gsamokovarov** [comment]
@panaak, can you install `2.1.0` (it was released recently) and try that as well? If it doesn't show the console, it will post a message on the Rails log looking like:

`Cannot render console from...` or `Cannot render console with content type...`

Can you show me this message if it happens at all?

**Comment by panaak** [comment]
ok, trying `2.1.0`:

`Cannot render console with content type application/x-www-form-urlencodedAllowed content types: [#<Mime::Type:0x00000003f2f5c8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">, #<Mime::Type:0x00000003f2f2d0 @synonyms=[], @symbol=:text, @string="text/plain">]`

my setting in development.rb:

  `config.web_console.automount = true
  config.web_console.whitelisted_ips =  %w( 127.0.0.1 )`

**Comment by gsamokovarov** [comment]
You can try adding this to your config:

```
config.web_console.acceptable_content_types =Mime::URL_ENCODED_FORM
```

Does it help? By the way where have you put this console? If its in a controller or a view, what is the action its in?

**Comment by panaak** [comment]
i tried adding this config option and now the console shows up, but it doesn't really work:

```
>>  1+1
Session fe346af2f7dacc790d44ee70c314e2bb is is no longer available in memory.

If you happen to run on a multi-process server (like Unicorn) the process
this request hit doesn't store fe346af2f7dacc790d44ee70c314e2bb in memory.
```

right now i put the `console` command in an EDIT action of a controller, before that i only waited for an error to occur..

**Comment by gsamokovarov** [comment]
Is this a development server you are running with apache and phusion passenger?

**Comment by panaak** [comment]
yes, develeopment debian server with apache + phusion passenger..

but wait, now it seems to be working.. first it said the session no longer exists, but when i try to visit another url with a different ID to edit in a controller, it works.. ??

**Comment by gsamokovarov** [comment]
I have to investigate the Phusion Passanger case, because I never used it and I don't know how request work inside of Apache sandbox. People usually run the console on their local machines where with `bundle exec rails server`.

Don't know if other people are using this machine as well, if that's the case I would advice to keep the console off of it. It may introduce great security issues – the console lets you execute arbitrary code on that server, say `system "cat #{Rails.root.join("config", "database.yml")}"` and an attacker can easily get the production database address and password if its hardcoded in the config.

**Comment by panaak** [comment]
thanx for investigating.. i'm really not sure about the environment of passenger sandbox really, so i won't be of much help here..

yes, i'm aware of the security concerns, but for development environment, which is all behind an http auth it really doesn't matter.. and i find the web-console a great tool for debugging.. untill now i used pry, which is also great, but your console looks better and more interconnected with the code.. .)

**Comment by VirtualPaul** [comment]
Was seeing this issue as well in a local environment with only a single process. Finally fixed by disabling caching for the view hosting the console: 

## web_console_controller.rb:
```
def console_view
  expires_now()
end
```

**Comment by gsamokovarov** [comment]
@VirtualPaul What version did this happened on? One of the latest ones that use ActionView for the template tooling?

**Comment by VirtualPaul** [comment]
@gsamokovarov 

Web-Console 2.1.3
Rails 4.0.2
Ruby 2.0.0
